apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "postgres-cluster.fullname" . }}
  labels:
{{- include "postgres-cluster.labels" . | nindent 4 }}
spec:
  numberOfInstances: {{ .Values.replicaCount }}
  dockerImage: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  resources:
{{- toYaml .Values.resources | nindent 4 }}

  postgresql:
    version: "14"
    parameters:
{{- toYaml .Values.postgresConfig | nindent 6 }}

  patroni:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    maximum_lag_on_failover: 33554432
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"

  volume:
    size: {{ .Values.storageCapacity }}
    storageClass: {{ .Values.storageClass }}
    accessMode: {{ .Values.accessModes }}

