apiVersion: v1
kind: Secret
metadata:
  name: postgres.{{ include "postgres-cluster.fullname" . }}
  labels:
{{- include "postgres-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: postgres
  password: {{ .Values.password }}
