apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgres-operator
  namespace: system-tce
spec:
  channel: stable
  installPlanApproval: Automatic
  name: postgres-operator
  source: daas-registry-postgres
  sourceNamespace: operator-hub
